name: backend

on:
  push:
    branches:
      - main

# ワーキングディレクトリを backend にする
defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Github上のソースコードを取得
      # - run: echo hello world

      - name: Current Direcotry
        run: pwd

      - name: ディレクトリ配下を閲覧
        run: ls -la
